statpro/devextreme-rails

app/assets/javascripts/data_table.js, app/helpers/data_table_helper.rb, app/views/data_tables/_data_table.html.haml, lib/data_table.rb, lib/data_table_formatters.rb
This is to allow the ability to have at least two data tables on a single screen.
Along with this, I have also updated the ability to create custom summaries.
=> DX-001 | Allow multiple Datatables per screen

app/assets/javascripts/data_table_templates.js, lib/data_table.rb, lib/data_table_formatters.rb
Allowed for the usage of timeago2 field.
Also allowed for the ability to have a text value show in a timeago field(This could potentially be used as an override).
=> DX-002 | Add TimeAgo2

lib/data_table.rb
With this change, one can change the source of the resultset that populated the datatable. And this also in turn allows for one to get the rowcount from another source too.
For instance...
I can override the get_resultset to retrieve the results from an api call, returning an array(not relation). And then I can override the get_row_count to retrieve the count from the length of the resultset array.
=> DX-003 | Allow for overriding of resultset and rowcount for datatable

Gemfile.lock, app/assets/stylesheets/master_detail.scss, lib/data_table.rb, lib/devextreme/rails/version.rb
There is an issue on multiselect grids, that one cannot select a row unless they specifically click the checkbox.
=> DX-010 | Fix multiselect row selection

Gemfile.lock, app/assets/javascripts/master_detail.js, app/helpers/data_table_helper.rb, app/views/data_tables/_data_table.html.haml, app/views/data_tables/_grid_toolbar.html.haml, lib/data_table.rb, lib/devextreme/rails/version.rb
The reset grid button does not work for child grids in a master detail setup.
=> DX-012 | Allow grid reset for master detail grids

Gemfile.lock, lib/data_table.rb, lib/data_table_formatters.rb, lib/devextreme/rails/version.rb
* Fixed space between fixed columns and data columns.
* Fixed error thrown when sorting while on a multiselect grid
* Re-enabled server-side sorting, filtering, and paging
* Bumped version
=> DX-014 | Stabilize DexEx DataGrid

Gemfile.lock, app/assets/javascripts/master_detail.js, app/helpers/data_table_helper.rb, lib/devextreme/rails/version.rb
* Added guard to selected row changed to check if there are any rows selected.
* Updated master_detail.js to not look up the grids all the time.
* Updated unregister of resize event to use current level grid id.
* Bumped version.
=> DX-016 | Fix multi-select on master-detail

Gemfile.lock, app/assets/javascripts/master_detail.js, lib/devextreme/rails/version.rb
* added a timeout with updateDimensions and repaint to the master-detail factory_reset function
=> DX-020 | Gap on auto width grid when fixed width column used

Gemfile.lock, app/helpers/data_table_helper.rb, app/views/data_tables/_data_table.html.haml, app/views/data_tables/_grid_toolbar.html.haml, lib/devextreme/rails/version.rb
* removed S3 specific code
* added download as xls button, not visible by default
=> DX-021 | Refactor grid_toolbar to be re-used between multiple projects

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
* passed options through and got :no_limit from them instead of params
=> DX-025 | Fix No-Limit on CSV Export

Gemfile.lock, app/views/data_tables/_data_table.html.haml, app/views/data_tables/_grid_toolbar.html.haml, lib/devextreme/rails/version.rb
Group grids were showing a blank result in the Row Count widget on first load when results were expanded/collapsed.
=> DX-032 | Row Count not showing value for grouped grids

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
and support .human method if implemented. i.e. for the Array Backed data tables you can implement the human method for a default download file name
=> isolatete activerecord relation logic.

app/assets/javascripts/data_table.js
=> DX-033 | Patch | Downloads not working properly for Master-Detail

Gemfile.lock, lib/devextreme/rails/version.rb
Clicking column headers causes issues when there is a fixed column in the grid.
=> DX-035 | Add check to allow sorting with fixed columns

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
The ColumnIcon was not showing tooltip on all rows and was also not handling the click properly.
=> DX-041 | BUG | Fix ColumnIcon to use tooltip and clicks properly

Gemfile.lock, app/assets/javascripts/data_table_templates.js, lib/data_table.rb, lib/devextreme/rails/version.rb
Needed to allow for overriding of the actions hash that is to be used in the json, so that I can apply classes based on permissions.
=> DX-047 | Allow for overriding of action classes

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
When this gem is used with Rails 5.1, it currently falls over when trying to return results for custom grids.
=> DX-050 | Cater for Rails 5.1

lib/data_table.rb
Removed code not needed in this version
=> DX-050 | Patch 1 | Cater for Rails 5.1

Gemfile.lock, app/views/data_tables/_data_table.html.haml, lib/devextreme/rails/version.rb
Currently, the old functionality of handling nulls for fields that would use cell_css_class, has been ignored. This change will bring that functionality into the new implementation.
=> DX-052 | Fix templating for cell_css_class

Gemfile.lock, app/assets/javascripts/data_table.js, lib/devextreme/rails/version.rb
Adding helper functions to be used in bulk actions.
=> DX-053 | Add bulk action helper

Gemfile.lock, lib/data_table.rb, lib/data_table_formatters.rb, lib/devextreme/rails/version.rb
in prep for [SCNINE-749](https://jira.statpro.com/browse/SCNINE-749)
=> DX-056 | add format_text and the head filter defaults

Gemfile.lock, app/helpers/data_table_helper.rb, lib/data_table.rb, lib/devextreme/rails/version.rb
=> SCNINE-749
=> Filter will fetch its data per column from a dynamic api endpoint
=> This PR is related to https://github.com/statpro/rc-ui/pull/862
=> Add custom filter functionality

Gemfile.lock, app/views/data_tables/_data_table.html.haml, lib/data_table.rb, lib/data_table_formatters.rb, lib/devextreme/rails/version.rb, lib/renderers/data_table_csv_renderer.rb, lib/renderers/data_table_xls_renderer.rb
=> Apply grid level filter for CSV and XLS download
=> add sortValue only when value is present
=> remove filter disabled option
=> SCNINE-1591 Apply grid level filter (v2)

Gemfile.lock, app/views/data_tables/_data_table.html.haml, lib/devextreme/rails/version.rb, lib/renderers/data_table_csv_renderer.rb, lib/renderers/data_table_xls_renderer.rb
=> Filter value in grid state is different from column filter value
=> So store column filter value in gridState as a different field
**Column filterOptions**
`filterOptions: [["vComposites.FirmShortName","=","First Asset Management"],"or",["vComposites.FirmShortName","=","First Private Banking"]]`
**gridState filterOptions**
`"filterValue":["vComposites.FirmShortName","anyof",["First Asset Management","First Private Banking"]]`
Two choices, I could rewrite the filter builder to cater for the anyof type or just store the same value on the custom save
=> use filter value from loadOptions

Gemfile.lock, app/assets/javascripts/data_table_templates.js, lib/data_table_formatters.rb, lib/devextreme/rails/version.rb
=> added column_template_popup formatter

Gemfile.lock, lib/devextreme/rails/version.rb, lib/renderers/data_table_xls_renderer.rb
=> query.any? results into issues with the activerecord-sqlserver-adapter in rails 6
=> SCNINE-1646 | Remove query.any?

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
=> SCNINE-2064 | Grid does not display results when a 2nd selection is made

Gemfile.lock, app/assets/javascripts/data_table.js, app/views/data_tables/_data_table.html.haml, lib/devextreme/rails/version.rb
W0017
Occurs if a component's width, height, or similar properties have a value of the function type.
=> DX-065 | Remove height function from datagrid

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
- DevExtreme needs to know the select_all_mode for inifinite scrolling
- bump version
=> DX 066 | DevExtreme needs to know the select_all_mode for inifinite scrolling

Gemfile.lock, app/assets/javascripts/data_table.js, lib/devextreme/rails/version.rb
- DX-067 | Revert Interpolation
- bump version
=> DX-067 | Revert Interpolation

Gemfile.lock, app/assets/javascripts/data_table_templates.js, lib/devextreme/rails/version.rb
- DX-069 | Make SyntaxHighlight Global
=> DX-069 | Make SyntaxHighlight Global

Gemfile.lock, app/assets/javascripts/master_detail.js, app/helpers/data_table_helper.rb, app/src/javascripts/devextreme.js, app/views/data_tables/_data_table.html.haml, lib/data_table.rb, lib/devextreme/rails/version.rb
- DX-072 | Fix alignment on 3rd level
- refactor
- make show_level_1 global
- fix height for certain 3rd level grids
- remove custom code in dx lib and reference npm lib
- fix resize issue when changing grid too fast
- bump version
=> DX-072 | Fix alignment on 3rd level

Gemfile.lock, app/views/data_tables/_data_table.html.haml, lib/devextreme/rails/version.rb
- DX-073 | Fix fixed height
- bump version
=> DX-073 | Fix fixed height

Gemfile.lock, devextreme-rails.gemspec, lib/devextreme/rails/version.rb
=> SCNINE-2305 | Upgrade all critical security alert dependencies on devextreme gem

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
=> SCNINE-2309 | RC-UI: upgrade rails to 6.1.7.3

.gitignore, Gemfile.lock, app/assets/javascripts/data_table.js, app/assets/javascripts/data_table_templates.js, app/assets/javascripts/master_detail.js, app/views/data_tables/_data_table.html.haml, lib/devextreme/rails/version.rb, package.json
- feat: update `jQuery` to v3
- feat: replace deprecated `selector` calls
- feat: replace deprecated delegate calls
- chore: refactor and cleanup
- fix: do not fail when using actions on the detail grid when it is not a grid
- chore: add `act` to `.gitignore`
- fix: replace deprecated `context` calls
RPLUS-8205
=> feat: updated `jquery` to v3

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
=> SCNINE-2791 | Financials/Composites/xxx/Accounts - Associations Filter broken - replace with Dropdown

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb
=> SCNINE-2937 | Data Extracts download

Gemfile.lock, app/assets/javascripts/data_table_templates.js, lib/devextreme/rails/version.rb
=> SCNINE-2220 | Workflow dashboard should display absolute date instead of relative date

Gemfile.lock, lib/data_table.rb, lib/devextreme/rails/version.rb, lib/renderers/data_table_csv_renderer.rb, lib/renderers/data_table_xls_renderer.rb
=> SCNINE-3037 | RC: The CSV grid download is incorrectly including hidden grid columns

.deepsource.toml, .editorconfig, .rubocop.yml, Gemfile.lock, lib/devextreme/rails/version.rb
- **chore(deps): add `.deepsource.toml`**
- **conf: add `.editorconfig`**
- **chore: bump version**
=> conf: add deepsource
